Bug fix: Rescue error when Geocoder API call fails
pixielabs/devise-recognisable pull request #90
Opened 2023-06-23 16:04 UTC by PatMiekina

## Context
If the Geocoder request fails the `Guard` errors. This means that no one can sign in at all. This PR allows the users to still sign in even if the Geocoder API is down.

## Changes
- Rescue the error if Geocoder request fails.
- Add test for error rescue.
- Add test for Rollbar receiving an error in debug mode in production and staging environment.

## Ticket
https://github.com/orgs/pixielabs/projects/4/views/1?pane=issue&itemId=29226244

2023-06-23 18:02 UTC, defaye requested changes
Let's isolate our exception handler around the Geocoder logic that performs an API request and recover from a more specific exception raised by the library, something like `Geocoder::Error` is fine.

We could perhaps introduce another configuration variable to help determine whether to log an error message, and based on that check alone, log to Rollbar. We can tidy up the spec to depend on this check instead.

It's worth checking with @JonathanAndrews if we really want to still return a `:complete_mismatch` if an exception occurs within the lookup.

2023-06-27 09:12 UTC, PatMiekina commented on app/lib/devise_recognisable/guard.rb
> +      current_sign_in = Geocoder.search(@request.location.ip).first
Yes, this is intentional.

2023-06-27 09:13 UTC, PatMiekina commented on app/lib/devise_recognisable/guard.rb
> +        require 'rollbar'
This has been only used here, because Rollbar is not used outside of `info_only` and `debug `modes.

2023-06-27 10:01 UTC, defaye requested changes
Minor changes

2023-06-27 10:01 UTC, defaye commented on spec/dummy-app/spec/lib/devise_recognisable/guard_spec.rb
> +        let(:error) {Geocoder::Error.new}
```
        let(:error) { Geocoder::Error.new 'server error.' }
```

Added some spacing, and an error description that matches how it's used in Geocoder.

2023-06-27 10:14 UTC, merged